import { Bike } from './types';

export const ADDITIONAL_BIKES: { scooters: Bike[]; motorcycles: Bike[]; ev: Bike[] } = {
    ev: [
        {
            id: 'activa-e',
            name: 'Activa e:',
            category: 'ev',
            image: '/images/honda_activa_110.png',
            fuel: 'Electric',
            series: 'Activa',
            segment: 'Scooter',
            slug: 'activa-e',
            description: 'The electric evolution of India\'s favorite scooter.',
            features: ['Swappable Battery', 'Digital Display', 'Smart Key', 'Fast Charging'],
            colors: ['Pearl Precious White', 'Matte Axis Grey Metallic', 'Matte Pearl Blue'],
            power: '6 kW',
            torque: '22 Nm',
            mileage: '100 km/charge',
            weight: '110 kg',
            seatHeight: '765 mm',
            brakes: 'Front: Disc, Rear: Drum',
            tyres: 'Tubeless, Front: 90/90-12, Rear: 90/100-10'
        },
        {
            id: 'qc1',
            name: 'QC1',
            category: 'ev',
            image: '/images/honda_dio_110.png',
            fuel: 'Electric',
            segment: 'Scooter',
            slug: 'qc1',
            description: 'Compact urban electric mobility for a sustainable future.',
            colors: ['Silver Metallic', 'Pearl White', 'Matte Black'],
            features: ['LED Lighting', 'Digital Meter', 'Eco Mode', 'Combined Braking System'],
            power: '4.5 kW',
            torque: '18 Nm',
            mileage: '80 km/charge',
            weight: '95 kg',
            seatHeight: '760 mm',
            brakes: 'Drum Brakes with CBS',
            tyres: 'Tubeless'
        }
    ],
    scooters: [
        {
            id: 'activa-110',
            name: 'Activa 110',
            category: 'scooter',
            cc: 109.51,
            price: 76234,
            image: '/images/honda_activa_110.png',
            series: 'Activa',
            segment: 'Commuter',
            fuel: 'Petrol',
            type: 'Scooter',
            slug: 'activa-110',
            colors: ['Decent Blue Metallic', 'Pearl Precious White', 'Black', 'Matte Axis Grey Metallic', 'Rebel Red Metallic'],
            features: ['eSP Technology', 'Engine Start/Stop Switch', 'Double Lid External Fuel Fill', 'Silent Start with ACG'],
            description: 'The game-changing scooter of India with unmatched reliability.',
            power: '5.74 kW @ 8000 rpm',
            torque: '8.90 Nm @ 5500 rpm',
            mileage: '50 kmpl',
            weight: '106 kg',
            seatHeight: '765 mm',
            brakes: 'Drum with CBS',
            tyres: 'Tubeless'
        },
        {
            id: 'activa-110-anniversary',
            name: 'Activa 110 Anniversary Edition',
            category: 'scooter',
            cc: 109.51,
            price: 78000,
            image: '/images/honda_activa_110.png',
            series: 'Activa',
            segment: 'Commuter',
            fuel: 'Petrol',
            type: 'Scooter',
            slug: 'activa-110-anniversary',
            featured: true,
            colors: ['Matte Mature Brown Metallic', 'Pearl Nightstar Black'],
            features: ['Golden Emblem', 'Premium Color Themes', 'eSP Technology', 'LED Headlamp'],
            description: 'Special edition Activa celebrating 20 years of legacy.',
            power: '5.74 kW @ 8000 rpm',
            torque: '8.90 Nm @ 5500 rpm',
            mileage: '50 kmpl',
            weight: '106 kg',
            seatHeight: '765 mm',
            brakes: 'Drum with CBS',
            tyres: 'Tubeless'
        },
        {
            id: 'activa-125',
            name: 'Activa 125',
            category: 'scooter',
            cc: 124,
            price: 85000,
            image: '/images/honda_activa_110.png',
            series: 'Activa',
            segment: 'Premium',
            fuel: 'Petrol',
            type: 'Scooter',
            slug: 'activa-125',
            colors: ['Heavy Grey Metallic', 'Midnight Blue Metallic', 'Pearl Precious White', 'Rebel Red Metallic'],
            features: ['Front Glove Box', 'Side Stand Engine Cut-off', 'Digital-Analog Meter', 'Smart Key System'],
            description: 'Premium urban scooter with 125cc power and refined comfort.',
            power: '6.11 kW @ 6500 rpm',
            torque: '10.4 Nm @ 5000 rpm',
            mileage: '48 kmpl',
            weight: '110 kg',
            seatHeight: '765 mm',
            brakes: 'Front: Disc / Rear: Drum CBS',
            tyres: 'Tubeless'
        },
        {
            id: 'activa-125-anniversary',
            name: 'Activa 125 Anniversary Edition',
            category: 'scooter',
            cc: 124,
            price: 87000,
            image: '/images/honda_activa_110.png',
            series: 'Activa',
            segment: 'Premium',
            fuel: 'Petrol',
            type: 'Scooter',
            slug: 'activa-125-anniversary',
            colors: ['Matte Marvel Blue', 'Pearl Nightstar Black'],
            features: ['Special Anniversary Badging', 'Chrome Accents', 'Smart Key System', 'Side Stand Engine Cut-off'],
            description: 'Exclusive anniversary edition with premium chrome details.',
            power: '6.11 kW @ 6500 rpm',
            torque: '10.4 Nm @ 5000 rpm',
            mileage: '48 kmpl',
            weight: '110 kg',
            seatHeight: '765 mm',
            brakes: 'Disc with CBS',
            tyres: 'Tubeless'
        },
        {
            id: 'dio-110',
            name: 'Dio 110',
            category: 'scooter',
            cc: 109.51,
            price: 74000,
            image: '/images/honda_dio_110.png',
            series: 'Dio',
            segment: 'Sporty',
            fuel: 'Petrol',
            type: 'Scooter',
            slug: 'dio-110',
            colors: ['Sports Red', 'Matte Axis Grey Metallic', 'Vibrant Orange', 'Matte Marvel Blue Metallic'],
            features: ['LED Position Lamp', 'Sporty Carbon Pattern Cover', 'External Fuel Lid', 'Digital Meter'],
            description: 'Keep motoing with the aggressively styled Dio.',
            power: '5.78 kW @ 8000 rpm',
            torque: '9.03 Nm @ 5250 rpm',
            mileage: '53 kmpl',
            weight: '105 kg',
            seatHeight: '765 mm',
            brakes: 'Drum with CBS',
            tyres: 'Tubeless'
        },
        {
            id: 'dio-125',
            name: 'Dio 125',
            category: 'scooter',
            cc: 123.9,
            price: 83400,
            image: '/images/honda_dio_110.png',
            series: 'Dio',
            segment: 'Sporty',
            fuel: 'Petrol',
            type: 'Scooter',
            slug: 'dio-125',
            colors: ['Pearl Nightstar Black', 'Matte Sangria Red Metallic', 'Sports Red', 'Matte Marvel Blue Metallic'],
            features: ['Dual Tip Muffler', 'Wave Disk Brake', 'Smart Key with H-Smart', 'Sporty Alloy Wheels'],
            description: 'Bold and aggressive 125cc scooter for the youth.',
            power: '6.09 kW @ 6250 rpm',
            torque: '10.4 Nm @ 5000 rpm',
            mileage: '48 kmpl',
            weight: '104 kg',
            seatHeight: '765 mm',
            brakes: 'Front: Disc, Rear: Drum CBS',
            tyres: 'Tubeless'
        },
        {
            id: 'dio-125-x',
            name: 'Dio 125 X-Edition',
            category: 'scooter',
            cc: 123.9,
            price: 85000,
            image: '/images/honda_dio_110.png',
            series: 'Dio',
            segment: 'Sporty',
            fuel: 'Petrol',
            type: 'Scooter',
            slug: 'dio-125-x',
            colors: ['Matte Axis Grey Metallic', 'Sports Red / Black'],
            features: ['X-Edition Graphics', 'Smart Key with H-Smart', 'Sporty Alloy Wheels', 'Telescopic Suspension'],
            description: 'Limited X-Edition Dio with exclusive racing graphics.',
            power: '6.09 kW @ 6250 rpm',
            torque: '10.4 Nm @ 5000 rpm',
            mileage: '48 kmpl',
            weight: '104 kg',
            seatHeight: '765 mm',
            brakes: 'Disc with CBS',
            tyres: 'Tubeless'
        }
    ],
    motorcycles: [
        {
            id: 'shine-100',
            name: 'Shine 100',
            category: 'motorcycle',
            cc: 100,
            price: 64900,
            image: '/images/honda_shine_100.png',
            series: 'Shine',
            segment: 'Commuter',
            fuel: 'Petrol',
            slug: 'shine-100',
            colors: ['Black with Gold Stripes', 'Black with Red Stripes', 'Black with Blue Stripes', 'Black with Green Stripes'],
            features: ['eSP Technology', 'Comfortable Long Seat', 'Halogen Headlamp', 'CBS with Equalizer'],
            description: 'Reliable and highly fuel-efficient everyday commuter.',
            power: '5.38 kW @ 7500 rpm',
            torque: '8.05 Nm @ 5000 rpm',
            mileage: '65 kmpl',
            weight: '99 kg',
            seatHeight: '786 mm',
            brakes: 'Drum Brakes with CBS',
            tyres: 'Tubeless'
        },
        {
            id: 'shine-100-dx',
            name: 'Shine 100 DX',
            category: 'motorcycle',
            cc: 100,
            price: 66000,
            image: '/images/honda_shine_100.png',
            series: 'Shine',
            segment: 'Commuter',
            fuel: 'Petrol',
            slug: 'shine-100-dx',
            colors: ['Black with Gold Stripes', 'Black with Red Stripes', 'Black with Grey Stripes'],
            features: ['Alloy Wheels', 'Self Start', 'Comfortable Long Seat', 'CBS with Equalizer'],
            description: 'Deluxe variant of the Shine 100 offering better styling and alloy wheels.',
            power: '5.38 kW @ 7500 rpm',
            torque: '8.05 Nm @ 5000 rpm',
            mileage: '65 kmpl',
            weight: '99 kg',
            seatHeight: '786 mm',
            brakes: 'Drum Brakes with CBS',
            tyres: 'Tubeless'
        },
        {
            id: 'shine-125',
            name: 'Shine 125',
            category: 'motorcycle',
            cc: 125,
            price: 79800,
            image: '/images/honda_shine_125.png',
            series: 'Shine',
            segment: 'Commuter',
            fuel: 'Petrol',
            slug: 'shine-125',
            colors: ['Black', 'Geny Grey Metallic', 'Rebel Red Metallic', 'Decent Blue Metallic'],
            features: ['Chrome Enhancements', '5-Speed Transmission', 'Silent Start with ACG', 'Engine Kill Switch'],
            description: 'India\'s favorite 125cc motorcycle combining power and elegance.',
            power: '7.9 kW @ 7500 rpm',
            torque: '11 Nm @ 6000 rpm',
            mileage: '55 kmpl',
            weight: '113 kg',
            seatHeight: '791 mm',
            brakes: 'Front: Disc / Drum, Rear: Drum',
            tyres: 'Tubeless'
        },
        {
            id: 'shine-125-limited',
            name: 'Shine 125 Limited Edition',
            category: 'motorcycle',
            cc: 125,
            price: 82000,
            image: '/images/honda_shine_125.png',
            series: 'Shine',
            segment: 'Commuter',
            fuel: 'Petrol',
            slug: 'shine-125-limited',
            colors: ['Matte Axis Grey Metallic', 'Matte Marvel Blue'],
            features: ['Special Golden Stripes', 'Premium Metallic Finishes', 'Silent Start with ACG', '5-Speed Transmission'],
            description: 'Limited Edition Shine 125 with premium graphics and finish.',
            power: '7.9 kW @ 7500 rpm',
            torque: '11 Nm @ 6000 rpm',
            mileage: '55 kmpl',
            weight: '113 kg',
            seatHeight: '791 mm',
            brakes: 'Disc / Drum with CBS',
            tyres: 'Tubeless'
        },
        {
            id: 'sp125',
            name: 'SP 125',
            category: 'motorcycle',
            cc: 125,
            price: 86000,
            image: '/images/honda_sp125.png',
            series: 'SP',
            segment: 'Commuter',
            fuel: 'Petrol',
            slug: 'sp-125',
            colors: ['Striking Green', 'Imperial Red Metallic', 'Pearl Igneous Black', 'Matte Axis Grey Metallic'],
            features: ['Fully Digital Meter', 'LED DC Headlamp', 'Wider Rear Tyre', 'Bold Edgy Styling'],
            description: 'Advanced sporty commuter with digital cluster and LED headlamp.',
            power: '8.0 kW @ 7500 rpm',
            torque: '10.9 Nm @ 6000 rpm',
            mileage: '60 kmpl',
            weight: '116 kg',
            seatHeight: '790 mm',
            brakes: 'Front: Disc / Rear: Drum with CBS',
            tyres: 'Tubeless'
        },
        {
            id: 'sp125-anniversary',
            name: 'SP 125 Anniversary Edition',
            category: 'motorcycle',
            cc: 125,
            price: 88000,
            image: '/images/honda_sp125.png',
            series: 'SP',
            segment: 'Commuter',
            fuel: 'Petrol',
            slug: 'sp-125-anniversary',
            colors: ['Matte Marvel Blue', 'Pearl Nightstar Black'],
            features: ['USB Type-C Charger', 'TFT Display Elements', 'Aggressive Tank Shrouds', 'LED Headlamp'],
            description: 'Special Anniversary edition featuring USB charging and exclusive styling.',
            power: '8.0 kW @ 7500 rpm',
            torque: '10.9 Nm @ 6000 rpm',
            mileage: '60 kmpl',
            weight: '116 kg',
            seatHeight: '790 mm',
            brakes: 'Disc with CBS',
            tyres: 'Tubeless'
        },
        {
            id: 'sp160',
            name: 'SP 160',
            category: 'motorcycle',
            cc: 162.71,
            price: 117500,
            image: '/images/honda_sp160.png',
            series: 'SP',
            segment: 'Sport Commuter',
            fuel: 'Petrol',
            slug: 'sp-160',
            colors: ['Matte Marvel Blue Metallic', 'Matte Axis Grey Metallic', 'Pearl Spartan Red', 'Pearl Igneous Black'],
            features: ['Aerodynamic Design', 'Engine Stop Switch', 'Hazard Switch', 'Petal Disk Brake'],
            description: 'Sporty and powerful 160cc street bike with aggressive aesthetics.',
            power: '9.9 kW @ 7500 rpm',
            torque: '14.58 Nm @ 5500 rpm',
            mileage: '45 kmpl',
            weight: '141 kg',
            seatHeight: '796 mm',
            brakes: 'Front: Disc, Rear: Disc / Drum',
            tyres: 'Tubeless 130mm Rear'
        },
        {
            id: 'livo',
            name: 'Livo',
            category: 'motorcycle',
            cc: 110,
            price: 78500,
            image: '/images/honda_livo_110.png',
            series: 'Livo',
            segment: 'Commuter',
            fuel: 'Petrol',
            slug: 'livo',
            colors: ['Athletic Blue Metallic', 'Matte Axis Grey Metallic', 'Imperial Red Metallic'],
            features: ['Sporty Tank Shrouds', 'Urban Styling', 'Integrated Headlamp Beam & Passing Switch', 'Service Due Indicator'],
            description: 'Stylish 110cc commuter designed to turn heads in the city.',
            power: '6.47 kW @ 7500 rpm',
            torque: '9.30 Nm @ 5500 rpm',
            mileage: '60 kmpl',
            weight: '113 kg',
            seatHeight: '790 mm',
            brakes: 'Front: Disc / Rear: Drum',
            tyres: 'Tubeless'
        },
        {
            id: 'unicorn',
            name: 'Unicorn',
            category: 'motorcycle',
            cc: 162.7,
            price: 109800,
            image: '/images/honda_unicorn_160.png',
            series: 'Unicorn',
            segment: 'Commuter',
            fuel: 'Petrol',
            slug: 'unicorn',
            colors: ['Imperial Red Metallic', 'Matte Axis Grey Metallic', 'Pearl Igneous Black'],
            features: ['Mono Shock Suspension', 'Engine Stop Switch', 'High Ground Clearance', 'Premium Chrome Accents'],
            description: 'Classic 160cc commuter delivering smooth power and unmatched comfort.',
            power: '9.5 kW @ 7500 rpm',
            torque: '14.0 Nm @ 5500 rpm',
            mileage: '50 kmpl',
            weight: '140 kg',
            seatHeight: '798 mm',
            brakes: 'Single Channel ABS',
            tyres: 'Tubeless'
        },
        {
            id: 'hornet-2-0',
            name: 'Hornet 2.0',
            category: 'motorcycle',
            cc: 184.4,
            price: 139000,
            image: '/images/honda_hornet_2_0.png',
            series: 'Hornet',
            segment: 'Sport',
            fuel: 'Petrol',
            slug: 'hornet-2-0',
            colors: ['Matte Sangria Red Metallic', 'Pearl Igneous Black', 'Matte Marvel Blue Metallic'],
            features: ['Assist & Slipper Clutch', 'USD Front Forks', 'Fully Digital Liquid Crystal Meter', 'All-LED Lighting'],
            description: 'Aggressive streetfighter born to rule the urban jungle.',
            power: '12.7 kW @ 8500 rpm',
            torque: '15.9 Nm @ 6000 rpm',
            mileage: '40 kmpl',
            weight: '142 kg',
            seatHeight: '790 mm',
            brakes: 'Dual Disc with Single Channel ABS',
            tyres: 'Front 110/70, Rear 140/70 Tubeless'
        },
        {
            id: 'cb300f',
            name: 'CB300F',
            category: 'motorcycle',
            cc: 293.5,
            price: 170000,
            image: '/images/honda_cb300f.png',
            series: 'CB',
            segment: 'Sport',
            fuel: 'Petrol',
            slug: 'cb300f',
            colors: ['Sports Red', 'Matte Axis Grey Metallic', 'Matte Marvel Blue'],
            features: ['Honda Selectable Torque Control (HSTC)', 'Assist & Slipper Clutch', 'Tapered Handlebar', 'Golden USD Forks'],
            description: 'Advanced 300cc streetfighter packed with performance and tech.',
            power: '18 kW @ 7500 rpm',
            torque: '25.6 Nm @ 5500 rpm',
            mileage: '30 kmpl',
            weight: '153 kg',
            seatHeight: '789 mm',
            brakes: 'Dual Channel ABS',
            tyres: 'Front 110/70, Rear 150/60 Radial'
        },
        {
            id: 'cb350',
            name: 'CB350',
            category: 'motorcycle',
            cc: 348.36,
            price: 199900,
            image: '/images/honda_cb350_hness.png',
            series: 'CB',
            segment: 'Premium',
            fuel: 'Petrol',
            type: 'Classic',
            slug: 'cb350',
            colors: ['Precious Red Metallic', 'Matte Marshal Green Metallic', 'Pearl Nightstar Black'],
            features: ['Honda Smartphone Voice Control system', 'Dual Channel ABS', 'Assist & Slipper Clutch', 'Selectable Torque Control'],
            description: 'A timeless classic redefined with modern performance and features.',
            power: '15.5 kW @ 5500 rpm',
            torque: '30 Nm @ 3000 rpm',
            mileage: '35 kmpl',
            weight: '181 kg',
            seatHeight: '800 mm',
            brakes: 'Dual Channel ABS',
            tyres: 'Tubeless'
        },
        {
            id: 'hness-cb350',
            name: 'H\'ness CB350',
            category: 'motorcycle',
            cc: 348.36,
            price: 209857,
            image: '/images/honda_cb350_hness.png',
            series: 'CB',
            segment: 'Premium',
            fuel: 'Petrol',
            type: 'Classic',
            slug: 'hness-cb350',
            colors: ['Matte Gunpowder Black Metallic', 'Precious Red Metallic', 'Pearl Nightstar Black'],
            features: ['Chrome Fuel Tank Elements', 'Half Duplex Cradle Frame', 'Hazard Switch', 'LED Headlamp & Winkers'],
            description: 'The pinnacle of classic touring, offering a majestic ride experience.',
            power: '15.5 kW @ 5500 rpm',
            torque: '30 Nm @ 3000 rpm',
            mileage: '35 kmpl',
            weight: '181 kg',
            seatHeight: '800 mm',
            brakes: 'Dual Channel ABS',
            tyres: 'Tubeless'
        },
        {
            id: 'cb350rs',
            name: 'CB350RS',
            category: 'motorcycle',
            cc: 348.36,
            price: 214856,
            image: '/images/honda_cb350_hness.png',
            series: 'CB',
            segment: 'Premium',
            fuel: 'Petrol',
            type: 'Scrambler',
            slug: 'cb350rs',
            colors: ['Athletic Blue Metallic', 'Matte Massive Grey Metallic', 'Radiant Red Metallic'],
            features: ['Tuck and Roll Seat', 'Under Seat Tail Lamp', 'Block Pattern Tyres', 'Skid Plate'],
            description: 'Scrambler-inspired CB350RS built for rugged aesthetics and comfort.',
            power: '15.5 kW @ 5500 rpm',
            torque: '30 Nm @ 3000 rpm',
            mileage: '35 kmpl',
            weight: '179 kg',
            seatHeight: '800 mm',
            brakes: 'Dual Channel ABS',
            tyres: 'Block Pattern Tubeless'
        },
        {
            id: 'nx500',
            name: 'NX500',
            category: 'motorcycle',
            cc: 471,
            price: 590000,
            image: '/images/honda_nx200.png',
            series: 'NX',
            segment: 'Adventure',
            fuel: 'Petrol',
            slug: 'nx500',
            colors: ['Grand Prix Red', 'Matte Gunpowder Black Metallic', 'Pearl Horizon White'],
            features: ['5-inch TFT Display', 'Honda RoadSync', 'HSTC', 'Showa 41mm SFF-BP USD Forks'],
            description: 'Compact and capable adventure machine for long journeys.',
            power: '35 kW @ 8600 rpm',
            torque: '43 Nm @ 6500 rpm',
            mileage: '27.7 kmpl',
            weight: '196 kg',
            seatHeight: '830 mm',
            brakes: 'Dual Channel ABS',
            tyres: 'Tubeless Adv Tyres'
        },
        {
            id: 'nx200',
            name: 'NX200',
            category: 'motorcycle',
            cc: 184.4,
            price: 147000,
            image: '/images/honda_nx200.png',
            series: 'NX',
            segment: 'Adventure',
            fuel: 'Petrol',
            slug: 'nx200',
            colors: ['Pearl Nightstar Black', 'Sports Red', 'Decent Blue Metallic'],
            features: ['Tall Wind Visor', 'Upswept Exhaust', 'Knuckle Guards', 'Liquid Crystal Meter'],
            description: 'Urban adventure-styled crossover motorcycle.',
            power: '12.7 kW @ 8500 rpm',
            torque: '15.9 Nm @ 6000 rpm',
            mileage: '40 kmpl',
            weight: '147 kg',
            seatHeight: '810 mm',
            brakes: 'Single Channel ABS',
            tyres: 'Block Pattern Non-radial'
        },
        {
            id: 'transalp-750',
            name: 'XL750 Transalp',
            category: 'motorcycle',
            cc: 755,
            price: 1099990,
            image: '/images/honda_xl750_transalp.png',
            series: 'XL',
            segment: 'Adventure',
            fuel: 'Petrol',
            slug: 'transalp-750',
            colors: ['Ross White', 'Matte Iridium Gray Metallic'],
            features: ['5 Riding Modes', 'Throttle By Wire', 'Spoked Wheels', 'TFT Display with Connectivity'],
            description: 'The legendary Transalp returns to conquer all terrains.',
            power: '67.5 kW @ 9500 rpm',
            torque: '75 Nm @ 7250 rpm',
            mileage: '23 kmpl',
            weight: '208 kg',
            seatHeight: '850 mm',
            brakes: 'Dual Channel ABS with Off-road Mode',
            tyres: 'Front 21", Rear 18" Spoked'
        },
        {
            id: 'goldwing',
            name: 'Gold Wing Tour',
            category: 'motorcycle',
            cc: 1833,
            price: 3916055,
            image: '/images/honda_xl750_transalp.png',
            series: 'Gold Wing',
            segment: 'Flagship',
            fuel: 'Petrol',
            type: 'Tourer',
            slug: 'goldwing',
            colors: ['Gunmetal Black Metallic', 'Candy Ardent Red'],
            features: ['7-Speed DCT', 'Apple CarPlay / Android Auto', 'Airbag', 'Electronic Suspension'],
            description: 'The ultimate luxury touring motorcycle with an iconic flat-six engine.',
            power: '93 kW @ 5500 rpm',
            torque: '170 Nm @ 4500 rpm',
            mileage: '18 kmpl',
            weight: '390 kg',
            seatHeight: '745 mm',
            brakes: 'Dual Channel ABS with CBS',
            tyres: 'Radial Tubeless'
        },
        {
            id: 'cbr1000rr-r',
            name: 'CBR1000RR-R Fireblade',
            category: 'motorcycle',
            cc: 999.9,
            price: 2300000,
            image: '/images/honda_cbr650r.png',
            series: 'CBR',
            segment: 'Flagship',
            fuel: 'Petrol',
            type: 'Supersport',
            slug: 'cbr1000rr-r',
            colors: ['Grand Prix Red', 'Matte Pearl Morion Black'],
            features: ['MotoGP Aerodynamics', 'Öhlins Smart EC Suspensions', 'Brembo Stylema Brakes', 'Titanium Exhaust'],
            description: 'Born to race, bringing Track performance to the road.',
            power: '160 kW @ 14500 rpm',
            torque: '113 Nm @ 12500 rpm',
            mileage: '16 kmpl',
            weight: '201 kg',
            seatHeight: '830 mm',
            brakes: 'Dual Channel ABS Track Focus',
            tyres: 'Pirelli Diablo Supercorsa SP'
        },
        {
            id: 'cbr650r',
            name: 'CBR650R',
            category: 'motorcycle',
            cc: 649,
            price: 935427,
            image: '/images/honda_cbr650r.png',
            series: 'CBR',
            segment: 'Sport',
            fuel: 'Petrol',
            slug: 'cbr650r',
            colors: ['Grand Prix Red', 'Matte Gunpowder Black Metallic'],
            features: ['Inline 4-Cylinder Power', 'Honda E-Clutch', 'HSTC', 'Showa SFF-BP Forks'],
            description: 'The perfect blend of fully faired supersport styling and everyday usability.',
            power: '64 kW @ 12000 rpm',
            torque: '57.5 Nm @ 8500 rpm',
            mileage: '20 kmpl',
            weight: '211 kg',
            seatHeight: '810 mm',
            brakes: 'Dual Channel ABS',
            tyres: 'Tubeless'
        },
        {
            id: 'cb650r',
            name: 'CB650R',
            category: 'motorcycle',
            cc: 649,
            price: 914813,
            image: '/images/honda_cb650r.png',
            series: 'CB',
            segment: 'Sport',
            fuel: 'Petrol',
            slug: 'cb650r',
            colors: ['Matte Gunpowder Black Metallic', 'Pearl Smoky Gray'],
            features: ['Neo Sports Café Design', 'Inline 4-Cylinder Engine', 'Honda E-Clutch', 'Full LED Lighting'],
            description: 'Stripped back neo-sports cafe styling with inline-4 performance.',
            power: '64 kW @ 12000 rpm',
            torque: '57.5 Nm @ 8500 rpm',
            mileage: '20 kmpl',
            weight: '205 kg',
            seatHeight: '810 mm',
            brakes: 'Dual Channel ABS',
            tyres: 'Tubeless'
        }
    ]
};
